apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mychart.fullname" . }}-awesome-cats-ingress
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/zone: public
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: alymkulovabk.online
    http:
      paths:
      - backend:
          service:
            name: '{{ include "mychart.fullname" . }}-frontend-service'
            port:
              number: 3000
        path: /?(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: '{{ include "mychart.fullname" . }}-backend-service'
            port:
              number: 3000
        path: /api/?(.*)
        pathType: ImplementationSpecific
  # tls:
  # - hosts:
  #   - alymkulovabk.online
  #   secretName: letsencrypt-production