apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-backend-service
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
  annotations:
spec:
  type: {{ .Values.backendService.type }}
  selector:
    app: backend
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.backendService.ports | toYaml | nindent 2 }}