apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: prometheus
  endpoints:
    - port: http
  namespaceSelector:
    matchNames:
      - monitoring